apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../../base

patches:
  - patch: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: gatekeeper-system
        labels:
          pod-security.kubernetes.io/audit: baseline
          pod-security.kubernetes.io/audit-version: v1.24
          pod-security.kubernetes.io/enforce: restricted
          pod-security.kubernetes.io/enforce-version: v1.24
          pod-security.kubernetes.io/warn: baseline
          pod-security.kubernetes.io/warn-version: v1.24
